import { GenerationProps } from './Generation'

export const generationListData: GenerationProps[] = [
  {
    name: 'Original',
    subtitle: 'Gen 1',
    indexMin: 1,
    indexMax: 151,
    yearMin: 1999,
    yearMax: 2000,
    setCount: 7,
    exampleImgSrc: '/images/pikachu-base-set.jpg',
  },
  {
    name: 'Neo',
    subtitle: 'Gen 2',
    indexMin: 152,
    indexMax: 251,
    yearMin: 2000,
    yearMax: 2002,
    setCount: 4,
    exampleImgSrc: '/images/pikachu-neo-genesis.jpg',
  },
  {
    name: 'Ruby & Sapphire',
    subtitle: 'Gen 3',
    indexMin: 252,
    indexMax: 386,
    yearMin: 2003,
    yearMax: 2007,
    setCount: 16,
    exampleImgSrc: '/images/pikachu-ex.jpg',
  },
  {
    name: 'Diamond & Pearl',
    subtitle: 'Gen 4',
    indexMin: 387,
    indexMax: 493,
    yearMin: 2007,
    yearMax: 2008,
    setCount: 7,
    exampleImgSrc: '/images/pikachu-diamond-pearl.webp',
  },
  {
    name: 'Black & White',
    subtitle: 'Gen 5',
    indexMin: 494,
    indexMax: 649,
    yearMin: 2011,
    yearMax: 2013,
    setCount: 11,
    exampleImgSrc: '/images/pikachu-black-white.webp',
  },
  {
    name: 'XY',
    subtitle: 'Gen 6',
    indexMin: 650,
    indexMax: 721,
    yearMin: 2013,
    yearMax: 2016,
    setCount: 12,
    exampleImgSrc: '/images/pikachu-xy.webp',
  },
  {
    name: 'Sun & Moon',
    subtitle: 'Gen 7',
    indexMin: 722,
    indexMax: 809,
    yearMin: 2017,
    yearMax: 2019,
    setCount: 12,
    exampleImgSrc: '/images/pikachu-sun-moon.webp',
  },
  {
    name: 'Sword & Shield',
    subtitle: 'Gen 8',
    indexMin: 810,
    indexMax: 907,
    yearMin: 2020,
    yearMax: 2023,
    setCount: 12,
    exampleImgSrc: '/images/pikachu-sword-shield.webp',
  },
  {
    name: 'Scarlet & Violet',
    subtitle: 'Gen 9',
    indexMin: 908,
    indexMax: 1025,
    yearMin: 2023,
    yearMax: 2025,
    setCount: 12,
    exampleImgSrc: '/images/pikachu-scarlet-violet.webp',
  },
]
