import { ExpansionData } from '../../../src/server/types/ExpansionData'
import {
  CARD_EXPANSION_FOSSIL_MOCK,
  CARD_EXPANSION_MCDONALD_MOCK,
  CARD_EXPANSION_ORIGINAL_MOCK,
  CARD_EXPANSION_PLATINUM_MOCK,
  CARD_EXPANSION_POP_MOCK,
} from './cardExpansion.mock'
import {
  EXPANSION_DATA_FOSSIL,
  EXPANSION_DATA_MCDONALD,
  EXPANSION_DATA_ORIGINAL,
  EXPANSION_DATA_PLATINUM,
  EXPANSION_DATA_POP,
} from './expansionData.mock'

export const EXPANSION_STORE_MAP_MOCK = new Map<number, ExpansionData>([
  [CARD_EXPANSION_ORIGINAL_MOCK.expansionId, EXPANSION_DATA_ORIGINAL],
  [CARD_EXPANSION_FOSSIL_MOCK.expansionId, EXPANSION_DATA_FOSSIL],
  [CARD_EXPANSION_PLATINUM_MOCK.expansionId, EXPANSION_DATA_PLATINUM],
  [CARD_EXPANSION_MCDONALD_MOCK.expansionId, EXPANSION_DATA_MCDONALD],
  [CARD_EXPANSION_POP_MOCK.expansionId, EXPANSION_DATA_POP],
])
